// Centrale begindata voor de hele applicatie
// State wordt beheerd in App.jsx zodat navigatie geen data verliest

export const INIT_VIDEOS = [
  {
    id: 1, status: 'goedgekeurd',
    titel: 'AI in het Hoger Onderwijs — Kansen en Uitdagingen',
    videoId: 'hJP5GqnTrNo',
    omschrijving: 'Een verkenning van hoe AI het hoger onderwijs transformeert en welke keuzes instellingen nu moeten maken.',
    trefwoorden: ['AI', 'Hoger Onderwijs', 'Didactiek'],
    spoor: 1, ingediendDoor: 'Kernteam AI-HUB', datum: '18 juni 2026',
    omhoog: 12, omlaag: 2,
  },
  {
    id: 2, status: 'goedgekeurd',
    titel: 'SURF: De toekomst van AI in Onderwijs',
    videoId: 'aircAruvnKk',
    omschrijving: 'SURF presenteert de visie op AI in het Nederlandse hoger onderwijs en wat dit betekent voor studenten en medewerkers.',
    trefwoorden: ['SURF', 'Strategie', 'Hoger Onderwijs'],
    spoor: 3, ingediendDoor: 'Kernteam AI-HUB', datum: '10 juni 2026',
    omhoog: 8, omlaag: 1,
  },
  {
    id: 3, status: 'goedgekeurd',
    titel: 'AI-Geletterdheid in de klas',
    videoId: 'ad79nYk2keg',
    omschrijving: 'Praktische aanpak voor docenten om AI-geletterdheid te integreren in het onderwijs.',
    trefwoorden: ['Geletterdheid', 'Docenten', 'Didactiek'],
    spoor: 4, ingediendDoor: 'OO&I', datum: '5 juni 2026',
    omhoog: 6, omlaag: 0,
  },
]

export const INIT_PILOTS = [
  {
    id: 1,
    naam: 'AI-Feedback in Schrijfonderwijs',
    academie: 'Academie Educatie',
    onderdeel: 'intern',
    platform: 'ChatGPT / OpenAI',
    status: 'Lopend',
    doel: 'Studenten krijgen automatische feedback op hun schrijfopdrachten met behulp van AI, waardoor de docent meer tijd heeft voor persoonlijke begeleiding.',
    bereiken: 'Betere schrijfvaardigheden studenten, hogere tevredenheid over feedback, tijdbesparing voor docenten.',
    spoor: 1, laag: 5,
    surf: 'Nee / niet van toepassing',
    trefwoorden: ['Feedback', 'Schrijven', 'Didactiek', 'Studenten'],
    ambities: ['studiesucces', 'uitval'],
    impactInschatting: 'gemiddeld',
    contactNaam: 'Projectteam Academie Educatie',
    contactEmail: '',
    startDatum: '2026-09',
    bronUrl: 'https://www.surf.nl/online-onderwijs',
    bronLabel: 'SURF — AVG en AI-tools in het onderwijs',
    updates: [
      { id: 1, datum: '15 juni 2026', tekst: 'Eerste tests met drie docenten afgerond. Studenten reageren positief op de snelheid van feedback. Aandachtspunt: de feedback is soms te generiek.', auteur: 'Projectteam' },
    ],
  },
  {
    id: 2,
    naam: 'AI-Feedback ChatGPT op scripties',
    academie: 'Meerdere academies',
    onderdeel: 'intern',
    platform: 'ChatGPT (zakelijke versie)',
    status: 'Verkenning',
    doel: 'Docenten experimenteren met ChatGPT om studenten sneller feedback te geven op scripties. Geen sandboxaanvraag nodig: NHL Stenden is gebruiker, niet aanbieder. Wel verplicht: verwerkersovereenkomst en DPIA.',
    bereiken: 'Snellere feedback, tijdbesparing docenten, bewustwording over verantwoord AI-gebruik bij toetsing.',
    spoor: 1, laag: 5,
    surf: 'Nee / niet van toepassing',
    trefwoorden: ['Feedback', 'Scripties', 'Toetsing', 'ChatGPT'],
    ambities: ['studiesucces'],
    impactInschatting: 'gemiddeld',
    contactNaam: 'AI Compliance Team',
    contactEmail: '',
    startDatum: '2026-09',
    bronUrl: 'https://pec.surf.nl/vernieuwde-surf-modelverwerkersovereenkomst-beschikbaar/',
    bronLabel: 'SURF — Model Verwerkersovereenkomst 4.0 (november 2024)',
    updates: [],
  },
  {
    id: 3,
    naam: 'Frisius MC AI-workshops',
    academie: 'Academie Verpleegkunde en Gezondheid',
    onderdeel: 'extern',
    platform: 'Diverse',
    status: 'In ontwikkeling',
    doel: 'Gezamenlijke AI-workshops tussen Frisius MC en NHL Stenden als onderdeel van de Friese AI-propositie. Focus op AI in de zorg: ambient listening, virtual nursing en ketenoverstijgende datakoppeling.',
    bereiken: 'Versterking samenwerking zorg en onderwijs, praktijkgericht AI-onderwijs in de zorgsector.',
    spoor: 5, laag: 5,
    surf: 'Nee / niet van toepassing',
    trefwoorden: ['Zorg', 'Frisius', 'Samenwerking', 'Workshop'],
    ambities: [],
    impactInschatting: 'hoog',
    contactNaam: 'Frisius MC en NHL Stenden Werkveld',
    contactEmail: '',
    startDatum: '2026-10',
    bronUrl: 'https://www.nhlstenden.com/nieuws-en-artikelen/met-het-frisiuslab-zetten-nhl-stenden-en-frisius-mc-vol-in-op-innovatie',
    bronLabel: 'NHL Stenden — FrisiusLab: zorg, onderwijs en onderzoek samen',
    updates: [],
  },
  {
    id: 4,
    naam: 'AMCE AI-Proeftuin — Overkoepelende pilot',
    academie: 'Academie Media, Commerce & Entrepreneurship',
    onderdeel: 'intern',
    platform: 'AI Sandbox, EduGenAI, Mistral AI, Claude',
    status: 'In ontwikkeling',
    doel: 'De Academie Media, Commerce & Entrepreneurship wil als proeftuin voor NHL Stenden ervaring opdoen met verantwoorde AI-oplossingen. Studenten worden opgeleid voor domeinen waarin AI grote impact heeft: communicatie, contentcreatie, marketing, commerce en ondernemerschap. Zonder gedeelde AI-voorzieningen ontstaat versnippering: medewerkers en studenten gebruiken eigen accounts, losse tools en uiteenlopende werkwijzen. De pilot biedt een veilige, gedeelde experimenteeromgeving voor vier werkpakketten: data- en workflow-AI (Gemini CLI + MCP), RAG-gestuurde AI-agents, visuele prototyping en evaluatie van agentic workflows met Claude naast Microsoft Copilot.',
    bereiken: 'Veilige experimenteerruimte voor onderwijs en onderzoek. AI-geletterdheid docenten, medewerkers en studenten structureel versterkt. Concrete prototypes direct bruikbaar in curricula en Ad-ontwikkeling. Inzicht in kosten, licentiemodellen en opschaalbaarheid. Minder afhankelijkheid van losse persoonlijke AI-accounts. Advies over governance en kostenmodel voor de hele hogeschool na evaluatie.',
    spoor: 1, laag: 5,
    surf: 'EduGenAI — verkenning als onderwijsplatform',
    trefwoorden: ['AMCE', 'Proeftuin', 'AI Sandbox', 'EduGenAI', 'Mistral', 'Claude', 'Agentic'],
    ambities: ['geletterdheid', 'studiesucces', 'professionalisering'],
    impactInschatting: 'hoog',
    contactNaam: 'Patrick Bemelmans, Alette Hospers, Frits van Essen',
    contactEmail: '',
    startDatum: '2026-09',
    bronUrl: '',
    bronLabel: 'Voorstel AI-pilot AMCE NHL Stenden v0.1',
    updates: [],
  },
  {
    id: 5,
    naam: 'WP1: Data- en workflow-AI met Gemini CLI & MCP',
    academie: 'Academie Media, Commerce & Entrepreneurship',
    onderdeel: 'intern',
    platform: 'Gemini CLI, MCP-servers, GA4, SEO-tools',
    status: 'In ontwikkeling',
    doel: 'Binnen opleidingen communicatie, marketing, content en commerce werken studenten en docenten steeds vaker met data uit verschillende bronnen: Google Analytics 4, SEO-data, CRM-data, social media analytics en API\'s van externe tools. Met Gemini CLI in combinatie met MCP-servers verkennen we hoe AI systemen op een gecontroleerde manier verbindt. Studenten leren hoe AI data kan ontsluiten, combineren en interpreteren, én waar menselijke controle noodzakelijk blijft. De nadruk ligt op professioneel oordeelsvermogen: kritisch kijken naar databronnen, datakwaliteit, bias en interpretatie.',
    bereiken: 'Werkend prototype voor een onderwijssetting waarin studenten meerdere databronnen (GA4, SEO, CRM) kunnen bevragen en analyseren met AI-ondersteuning. Didactisch format voor data-informed werken met AI-assistentie. Bewustwording over datakwaliteit, bias en menselijke controle.',
    spoor: 2, laag: 4,
    surf: 'Nee / niet van toepassing',
    trefwoorden: ['Data', 'Workflow', 'Gemini', 'MCP', 'Marketing', 'Analytics'],
    ambities: ['geletterdheid', 'werkveld'],
    impactInschatting: 'gemiddeld',
    contactNaam: 'Patrick Bemelmans',
    contactEmail: '',
    startDatum: '2026-09',
    bronUrl: '',
    bronLabel: 'AMCE AI-pilot WP1 — Data & Workflow',
    updates: [],
  },
  {
    id: 6,
    naam: 'WP2: RAG-agents voor onderwijs en kennisdeling',
    academie: 'Academie Media, Commerce & Entrepreneurship',
    onderdeel: 'intern',
    platform: 'RAG, LLM naar keuze, gevalideerde academiedocumenten',
    status: 'In ontwikkeling',
    doel: 'RAG-gestuurde AI-agents gevoed met gevalideerde academiedocumenten zoals OER, handleidingen, rubrics, beroepsprofielen, toetsinformatie en projectdocumentatie. De agent fungeert niet als vervanging van de docent of begeleider, maar als ondersteunende laag die informatie toegankelijker maakt. Mogelijke toepassingen: een agent die docenten helpt bij het vertalen van AI-geletterdheid naar leeractiviteiten, een agent die studenten uitleg geeft over beroepsproducten en beoordelingscriteria, een agent die nieuwe docenten ondersteunt bij het vinden van curricula en toetsingsafspraken, en een agent die onderwijsontwikkelaars helpt bij het doorzoeken en vergelijken van opleidingsdocumenten. Duidelijke spelregels over bronnen, eigenaarschap en betrouwbaarheid zijn verplicht onderdeel van de pilot.',
    bereiken: 'Twee of drie geteste en gedocumenteerde AI-agents inclusief bronbeheer, versiebeheer, gebruiksinstructie en evaluatie op betrouwbaarheid. Bewezen dat AI kennisdeling kan versterken zonder formele beoordeling of besluitvorming over te nemen.',
    spoor: 1, laag: 4,
    surf: 'Nee / niet van toepassing',
    trefwoorden: ['RAG', 'AI-agent', 'Kennisdeling', 'Onderwijs', 'Documenten'],
    ambities: ['studiesucces', 'professionalisering'],
    impactInschatting: 'hoog',
    contactNaam: 'Alette Hospers',
    contactEmail: '',
    startDatum: '2026-09',
    bronUrl: '',
    bronLabel: 'AMCE AI-pilot WP2 — RAG-agents',
    updates: [],
  },
  {
    id: 7,
    naam: 'WP3: Visuele AI-prototyping voor Ad-ontwikkeling',
    academie: 'Academie Media, Commerce & Entrepreneurship',
    onderdeel: 'intern',
    platform: 'Beeldgeneratie AI',
    status: 'In ontwikkeling',
    doel: 'Voor Associate degree-ontwikkeling en praktijkgericht onderwijs is snel visualiseren van ideeën van grote waarde. Met beeldgeneratie-AI kunnen studenten en docenten in korte tijd campagneconcepten, interfaces, klantreizen, persona\'s, advertenties, merkbeelden en moodboards verkennen. Toepassingen: snel prototypen van campagneconcepten, visualiseren van retail- of hospitalityconcepten, ontwikkelen van social media formats, verkennen van merkidentiteit en tone-of-visual, maken van mock-ups voor websites en apps, en ondersteunen van brainstorms met werkveldpartners. Studenten leren ook kritisch beoordelen van AI-gegenereerd beeld op kwaliteit, inclusie, stereotypering, auteursrecht en ethiek. AI versnelt het ontwerpproces maar vervangt niet het professionele oordeel of de creativiteit van student en docent.',
    bereiken: 'Didactisch format voor verantwoord gebruik van image generation in ontwerpgerichte onderwijsactiviteiten. Voorbeeldopdrachten en beoordelingscriteria voor AI-ondersteund ontwerponderwijs. Inzicht in ethische aandachtspunten bij beeldgeneratie in een onderwijscontext.',
    spoor: 1, laag: 3,
    surf: 'Nee / niet van toepassing',
    trefwoorden: ['Beeldgeneratie', 'Prototyping', 'Design', 'Ad-ontwikkeling', 'Creativiteit'],
    ambities: ['geletterdheid', 'werkveld'],
    impactInschatting: 'gemiddeld',
    contactNaam: 'Frits van Essen',
    contactEmail: '',
    startDatum: '2026-09',
    bronUrl: '',
    bronLabel: 'AMCE AI-pilot WP3 — Visuele prototyping',
    updates: [],
  },
  {
    id: 8,
    naam: 'WP4: Evaluatie agentic workflows — Claude vs Copilot',
    academie: 'Academie Media, Commerce & Entrepreneurship',
    onderdeel: 'intern',
    platform: 'Claude (Anthropic), Microsoft Copilot',
    status: 'In ontwikkeling',
    doel: 'Naast Microsoft Copilot verkennen we een Claude-omgeving voor het evalueren van agentic workflows. Waar Copilot sterk verbonden is met de Microsoft 365-omgeving en dagelijkse productiviteitstoepassingen, kan Claude worden gebruikt als aanvullende experimenteeromgeving voor complexere AI-workflows: redeneren, documentanalyse, taakopdeling, iteratief werken en samenwerking tussen mens en AI. Claude wordt niet gepositioneerd als vervanging van Copilot, maar als vergelijkings- en evaluatieomgeving. De centrale vraag: welke typen AI-werkprocessen passen het best bij Copilot, en voor welke taken heeft een aparte agentic AI-omgeving meerwaarde? De evaluatie levert inzicht op in of en hoe agentic workflows verantwoord kunnen worden ingezet binnen onderwijsontwikkeling, kennisdeling en praktijkgerichte leeromgevingen.',
    bereiken: 'Evaluatie van bruikbaarheid, veiligheid, kosten, outputkwaliteit, transparantie, beheerbaarheid en didactische toepasbaarheid van agentic workflows. Helder advies over welke taken bij Copilot horen en welke bij een agentic AI-omgeving. Leidraad voor verantwoorde inzet van agentic AI in onderwijsontwikkeling.',
    spoor: 2, laag: 4,
    surf: 'Nee / niet van toepassing',
    trefwoorden: ['Agentic', 'Claude', 'Copilot', 'Workflow', 'Evaluatie'],
    ambities: ['professionalisering', 'werkveld'],
    impactInschatting: 'hoog',
    contactNaam: 'Patrick Bemelmans',
    contactEmail: '',
    startDatum: '2026-09',
    bronUrl: '',
    bronLabel: 'AMCE AI-pilot WP4 — Agentic workflows',
    updates: [],
  },
]

export const INIT_DOCS = [
  { id: 1, titel: 'AI Kompas NHL Stenden', categorie: 'strategie', spoor: null, type: 'pdf', datum: 'Juni 2026', omschrijving: 'Strategisch overzicht van de AI-architectuur en het vijflagenmodel.', icon: '📄', bestand: '/docs/NHL_Stenden_AI_Compass Definitief.pdf' },
  { id: 2, titel: 'AI Whitepaper NHL Stenden v9', categorie: 'strategie', spoor: null, type: 'pdf', datum: 'April 2026', omschrijving: 'Whitepaper over de strategische AI-koers van NHL Stenden. Uitgewerkte visie op verantwoorde AI-inzet.', icon: '📄', bestand: '/docs/whitepaper_AI_koers_NHL_Stenden_v09.pdf' },
  { id: 3, titel: 'Analyse AI-gebruik NHL Stenden', categorie: 'strategie', spoor: null, type: 'pdf', datum: 'April 2026', omschrijving: 'Analyse van huidig AI-gebruik binnen NHL Stenden. Inzicht in welke tools worden ingezet en door wie.', icon: '📊', bestand: '/docs/Analyse_AI_Gebruik_NHL_Stenden.pdf' },
  { id: 4, titel: 'AI en Werk', categorie: 'werken', spoor: 2, type: 'pdf', datum: 'April 2026', omschrijving: 'Document over de impact van AI op werk en werkprocessen binnen NHL Stenden.', icon: '⚙️', bestand: '/docs/ai-en-werk.pdf' },
  { id: 5, titel: 'WEF Future of Jobs Report 2025', categorie: 'werkveld', spoor: 5, type: 'pdf', datum: 'Maart 2026', omschrijving: 'World Economic Forum rapport over de toekomst van werk in het AI-tijdperk. Relevante context voor NHL Stenden als opleider.', icon: '🌍', bestand: '/docs/WEF_Future_of_Jobs_Report_2025.pdf' },
  { id: 6, titel: 'Kennisnet - Aan de slag met digitale geletterdheid', categorie: 'geletterdheid', spoor: 4, type: 'pdf', datum: 'Maart 2025', omschrijving: 'Praktische gids van Kennisnet voor het werken aan digitale geletterdheid in het onderwijs.', icon: '📖', bestand: '/docs/Kennisnet-ICILS-Aan-de-slag-met-digitale-geletterdheid.pdf' },
  { id: 7, titel: 'TRAI Document', categorie: 'governance', spoor: 3, type: 'pdf', datum: 'April 2026', omschrijving: 'Intern document over Transparantie, Risico, AI en Integriteit bij NHL Stenden.', icon: '⚖️', bestand: '/docs/TRAI-document.pdf' },
  { id: 8, titel: 'Digital Sovereignty Radar', categorie: 'governance', spoor: 3, type: 'pdf', datum: 'Maart 2026', omschrijving: 'Overzicht van digitale soevereiniteitsthemas en positionering van NHL Stenden daarin.', icon: '🎯', bestand: '/docs/Digital_Sovereignty_Radar.pdf' },
  { id: 9, titel: 'AI Regulatory Sandbox - Infoplaat', categorie: 'governance', spoor: 3, type: 'afbeelding', datum: 'Maart 2026', omschrijving: 'Visuele samenvatting van de AI Regulatory Sandbox: wat het is, wanneer relevant en de beslisboom.', icon: '🖼️', bestand: '/docs/InfoPlaat-sandbox.png' },
  { id: 10, titel: 'NVAO Startverkenning Generatieve AI', categorie: 'onderzoek', spoor: 6, type: 'pdf', datum: 'Januari 2026', omschrijving: 'Thematische analyse van generatieve AI in visitatierapporten. Conclusie: focus op toetsing, integrale aanpak ontbreekt.', icon: '📊', bestand: '/docs/Startverkenning_Generatieve_Artificiele_Intelligentie.pdf' },
  { id: 11, titel: 'AI Compliance Voortgangsrapportage', categorie: 'governance', spoor: 3, type: 'pdf', datum: 'Februari 2026', omschrijving: 'Rapportage AI Compliance Team aan CvB. Kernboodschap: AI leeft sterk maar centrale regie ontbreekt.', icon: '📋', bestand: '/docs/Voortgangsrapportage_AI_Compliance_v1.pdf' },
  { id: 12, titel: 'Programmavoorstel Bach - Digitale Autonomie', categorie: 'strategie', spoor: 6, type: 'pdf', datum: 'Januari 2026', omschrijving: 'Nationaal onderwijsversterkingsprogramma voor digitale soevereiniteit. Vier programmalijnen, investering 94 miljoen euro.', icon: '🏛️', bestand: '/docs/Programmavoorstel Bach - digitale autonomie en soevereiniteit.pdf' },
  { id: 13, titel: 'AI Regulatory Sandbox Praktijkgids', categorie: 'governance', spoor: 3, type: 'pdf', datum: '2026', omschrijving: 'Praktijkgids voor NHL Stenden: wanneer wel en niet een regulatory sandbox aanvragen. Inclusief beslisboom en stappenplan.', icon: '⚖️', bestand: '/docs/regulatory_sandbox_ai_NHL_Stenden.pdf' },
  { id: 14, titel: 'Friese AI-behoeften werksessie', categorie: 'samenwerking', spoor: 5, type: 'pdf', datum: 'Januari 2026', omschrijving: 'Uitwerking werksessie Friese AI-propositie met Frisius MC, NHL Stenden en Firda.', icon: '🤝', bestand: '/docs/Terugkoppeling werksessie 19 januari.pdf' },
  { id: 15, titel: 'Gartner Hype Cycle AI 2025', categorie: 'strategie', spoor: null, type: 'afbeelding', datum: 'Juni 2025', omschrijving: 'Gartner Hype Cycle voor AI 2025. Sovereign AI en AI Agents bovenaan de piek van verwachtingen.', icon: '📈', bestand: '/docs/Hype_Cycle_for_Artificial_Intelligence_2025.jpeg' },
]

export const INIT_EVENEMENTEN = [
  {
    id: 1,
    naam: 'AI-Netwerk Kick-off Bijeenkomst',
    locatie: 'NHL Stenden Leeuwarden, Rengerslaan 8',
    datum: '2026-09-10',
    startTijd: '13:00',
    eindTijd: '16:00',
    omschrijving: 'Officiele lancering van het AI-Netwerk. Kennismaking met het kernteam en netwerken.',
    organisator: 'Kernteam AI-Netwerk',
    sporen: [1, 2, 3, 4],
    kleur: '#1E3A8A',
  },
  {
    id: 2,
    naam: 'SURF Denktank - AI in Onderwijs',
    locatie: 'SURF Utrecht',
    datum: '2026-09-24',
    startTijd: '10:00',
    eindTijd: '15:00',
    omschrijving: 'Strategische sessie over AI in het Nederlandse hoger onderwijs.',
    organisator: 'SURF',
    sporen: [1, 3],
    kleur: '#065F46',
  },
]

export const INIT_LINKJES = [
  { id: 1, titel: 'Intranet NHL Stenden', url: 'https://nhlstenden.sharepoint.com', omschrijving: 'Het centrale intranet voor medewerkers.', intern: true, categorie: 'intranet', spoor: null, laag: null, trefwoorden: ['Intranet', 'Medewerkers'], toegevoegdDoor: 'Kernteam AI-HUB', datum: 'Juni 2026' },
  { id: 2, titel: 'SURF AI-HUB', url: 'https://www.surf.nl/themas/artificial-intelligence/ai-in-het-onderwijs', omschrijving: 'SURF pagina over AI in het onderwijs: tools, beleid, praktijkvoorbeelden en richtlijnen voor hoger onderwijs.', categorie: 'extern', spoor: 3, laag: 3, trefwoorden: ['SURF', 'AI', 'Soevereiniteit'], toegevoegdDoor: 'Kernteam AI-HUB', datum: 'Juni 2026' },
  { id: 3, titel: 'RDI - AI Regulatory Sandbox', url: 'https://www.rdi.nl', omschrijving: 'Rijksinspectie Digitale Infrastructuur. Beheerder van de Nederlandse AI Regulatory Sandbox, operationeel augustus 2026.', categorie: 'extern', spoor: 3, laag: 4, trefwoorden: ['AI Act', 'Compliance', 'Overheid'], toegevoegdDoor: 'Kernteam AI-Netwerk', datum: 'Juni 2026' },
  { id: 4, titel: 'Autoriteit Persoonsgegevens - AI', url: 'https://www.autoriteitpersoonsgegevens.nl', omschrijving: 'AP co-beheert de Nederlandse Regulatory Sandbox. Informatie over DPIA, AVG en AI-toepassingen met persoonsgegevens.', categorie: 'extern', spoor: 3, laag: 4, trefwoorden: ['Privacy', 'AVG', 'DPIA'], toegevoegdDoor: 'Kernteam AI-Netwerk', datum: 'Juni 2026' },
  { id: 5, titel: 'Npuls Expeditie AI', url: 'https://npuls.nl', omschrijving: 'Nationaal programma van mbo, hbo, wo en SURF voor AI in het onderwijs. Bundelt initiatieven rond AI in toetsing, curriculum en docentprofessionalisering.', categorie: 'extern', spoor: 1, laag: 5, trefwoorden: ['Nationaal', 'Onderwijs', 'Samenwerking'], toegevoegdDoor: 'Kernteam AI-Netwerk', datum: 'Juni 2026' },
  { id: 6, titel: 'Programma Bach - Universiteit van het Noorden', url: 'https://www.uvan.nl', omschrijving: 'Nationaal onderwijsversterkingsprogramma voor digitale autonomie en soevereiniteit. Geinitieerd vanuit Noord-Nederland, nationaal opschaalbaar.', categorie: 'extern', spoor: 6, laag: 3, trefwoorden: ['Soevereiniteit', 'Bach', 'Onderwijs'], toegevoegdDoor: 'Kernteam AI-Netwerk', datum: 'Juni 2026' },
  { id: 7, titel: "I'M A.I. — AI-initiatief NHL Stenden", url: 'https://www.nhlstenden.com/onderzoek/lectoraten/computer-vision-data-science/IMAI', omschrijving: 'Het NHL Stenden initiatief dat AI-technologie en toepassingen samenbrengt via vier communities: Research, Learning, Business en Experience Center.', categorie: 'onderzoek', spoor: 6, laag: 3, intern: false, trefwoorden: ['Onderzoek', 'AI', 'Lectoraat', 'Innovatie'], toegevoegdDoor: 'Kernteam AI-Netwerk', datum: 'Juni 2026' },
  { id: 8, titel: 'Lectoraat Computer Vision & AI', url: 'https://www.nhlstenden.com/onderzoek/lectoraten/computer-vision-artificial-intelligence', omschrijving: 'Het lectoraat CV&AI loopt voorop in toegepast AI-onderzoek bij NHL Stenden. Meer dan twee decennia ervaring in het integreren van AI in organisaties.', categorie: 'onderzoek', spoor: 6, laag: 3, intern: false, trefwoorden: ['Lectoraat', 'Computer Vision', 'Onderzoek'], toegevoegdDoor: 'Kernteam AI-Netwerk', datum: 'Juni 2026' },
  { id: 9, titel: 'Minor AI in Practice', url: 'https://www.nhlstenden.com/en/minors/ai-in-practice', omschrijving: 'Minor voor studenten die AI willen onderzoeken en toepassen in echte beroepspraktijk. Twee tracks: AI for Everyone en AI for Image Data.', categorie: 'onderwijs', spoor: 1, laag: 5, intern: false, trefwoorden: ['Minor', 'Studenten', 'Curriculum', 'AI'], toegevoegdDoor: 'Kernteam AI-Netwerk', datum: 'Juni 2026' },
  { id: 10, titel: 'Minor Decision Making & Generative AI', url: 'https://www.nhlstenden.com/en/minors/decision-making-and-generative-ai', omschrijving: 'Minor over AI-ondersteunde besluitvorming, kritisch denken en data-analyse. Inclusief module over generatieve AI en ethische implicaties.', categorie: 'onderwijs', spoor: 1, laag: 5, intern: false, trefwoorden: ['Minor', 'Generatieve AI', 'Ethiek', 'Besluitvorming'], toegevoegdDoor: 'Kernteam AI-Netwerk', datum: 'Juni 2026' },
  { id: 11, titel: 'CTL — AI & Toetsing, richtlijnen en beoordelen', url: 'https://newuniversity.sharepoint.com/sites/center-for-teaching-and-learning/SitePages/AI---toetsing,-richtlijnen-en-beoordeling.aspx', omschrijving: 'Intranetpagina van het Centre for Teaching and Learning met NHL Stenden richtlijnen voor AI en toetsing, adviezen voor examencommissies en stappenplan bij fraude.', categorie: 'beleid', spoor: 3, laag: 4, intern: true, trefwoorden: ['Toetsing', 'Beleid', 'ExCies', 'GenAI'], toegevoegdDoor: 'Kernteam AI-Netwerk', datum: 'Juni 2026' },
  { id: 12, titel: 'CTL — AI in je studie', url: 'https://newuniversity.sharepoint.com/sites/center-for-teaching-and-learning/SitePages/AI-in-je-studie.aspx', omschrijving: 'Intranetpagina van het CTL met informatie voor studenten over verantwoord AI-gebruik in de studie bij NHL Stenden.', categorie: 'beleid', spoor: 1, laag: 5, intern: true, trefwoorden: ['Studenten', 'AI', 'CTL', 'Beleid'], toegevoegdDoor: 'Kernteam AI-Netwerk', datum: 'Juni 2026' },
  { id: 14, titel: 'SURF Communities — Lesmaterialen AI-geletterdheid', url: 'https://communities.surf.nl/ai-in-education/artikel/lesmaterialen-over-ai-geletterdheid', omschrijving: 'Overzicht van lesmaterialen voor AI-geletterdheid in het onderwijs: e-modules, toolkits en handleidingen voor docenten en studenten.', categorie: 'extern', spoor: 4, laag: 5, intern: false, trefwoorden: ['Geletterdheid', 'Lesmaterialen', 'Docenten', 'SURF'], toegevoegdDoor: 'Kernteam AI-Netwerk', datum: 'Juni 2026' },
  { id: 15, titel: 'SURF Communities — AI verantwoord gebruik in onderwijs', url: 'https://communities.surf.nl/vraagbaak-online-onderwijs/artikel/hoe-gebruik-je-ai-verantwoord-in-je-onderwijs-denk-vooraf-altijd', omschrijving: 'Praktisch artikel over verantwoord AI-gebruik in het onderwijs: risicos, AVG, AI Act en wat docenten en instellingen moeten weten.', categorie: 'extern', spoor: 3, laag: 4, intern: false, trefwoorden: ['Verantwoord gebruik', 'AVG', 'AI Act', 'Risico'], toegevoegdDoor: 'Kernteam AI-Netwerk', datum: 'Juni 2026' },
  { id: 13, titel: 'CTL — AI-webinars van Npuls', url: 'https://newuniversity.sharepoint.com/sites/center-for-teaching-and-learning/SitePages/AI-webinars-van-Npuls.aspx', omschrijving: 'Overzicht van Npuls AI-webinars beschikbaar via het CTL intranet. Actuele professionalisering voor docenten en medewerkers.', categorie: 'onderwijs', spoor: 4, laag: 5, intern: true, trefwoorden: ['Npuls', 'Webinar', 'Professionalisering', 'Docenten'], toegevoegdDoor: 'Kernteam AI-Netwerk', datum: 'Juni 2026' },
]

export const INIT_INSPIRATIES = [
  { id: 1001, type: 'initiatief', icon: '🎯', typelabel: 'Visie & aanpak', rol: 'Academie', naam: 'AMCE NHL Stenden', spoor: 4, sporeDef: { titel: 'AI & Geletterdheid', icon: '📖' }, laag: null, titel: 'Human Value AI — de professional als regisseur', tekst: 'De meerwaarde van studenten in AI-tijdperk ligt niet in concurreren met AI, maar in het kunnen sturen, beoordelen, contextualiseren en verantwoord toepassen ervan. De Academie Media, Commerce & Entrepreneurship hanteert het concept Human Value AI: de professional van de toekomst gebruikt AI om betere vragen te stellen, sneller scenario\'s te ontwikkelen, data kritischer te interpreteren en waarde te creerëren voor mens, organisatie en samenleving. Docenten, studenten en medewerkers hebben daarvoor toegang nodig tot veilige, actuele en krachtige AI-voorzieningen. Zonder gedeelde voorzieningen blijven instellingen afhankelijk van losse experimenten en individuele accounts. De AMCE AI-proeftuin vertaalt deze visie naar concrete onderwijspraktijk via vier werkpakketten: data-AI, RAG-agents, visuele prototyping en evaluatie van agentic workflows.', url: '', datum: 'Juni 2026', trefwoorden: ['Human Value AI', 'Professionalisering', 'Regie', 'Proeftuin', 'AMCE'] },
  { id: 2, type: 'initiatief', icon: '🚀', typelabel: 'Initiatief of project', rol: 'Docent', naam: 'Anoniem', spoor: 1, sporeDef: { titel: 'AI & Leren', icon: '🎓' }, laag: 5, titel: 'AI-integratie in de PABO-opleiding', tekst: 'Wij zijn bezig met het integreren van AI-geletterdheid in het curriculum van de PABO.', url: '', datum: '12 juni 2026', trefwoorden: ['PABO', 'Curriculum', 'Geletterdheid'], stemmen: { omhoog: 8, omlaag: 1 } },
  { id: 4, type: 'artikel', icon: '📰', typelabel: 'Artikel of publicatie', rol: 'Medewerker dienst', naam: 'CTL NHL Stenden', intern: true, spoor: 3, sporeDef: { titel: 'AI & Verantwoordelijkheid', icon: '⚖️' }, laag: 4, titel: 'NHL Stenden kiest geen AI-detector voor toetsing', bronLabel: 'CTL NHL Stenden — AI & Toetsing, richtlijnen en beoordelen', tekst: 'NHL Stenden heeft bewust gekozen geen AI-detector aan te schaffen. Detectoren zijn niet betrouwbaar en effectieve detectie wordt steeds lastiger. Het beleid focust op sterk toetsontwerp en heldere toetsinstructie.', url: 'https://newuniversity.sharepoint.com/sites/center-for-teaching-and-learning/SitePages/AI---toetsing,-richtlijnen-en-beoordeling.aspx', datum: '25 juni 2026', trefwoorden: ['Toetsing', 'Beleid', 'GenAI', 'CTL'], stemmen: { omhoog: 0, omlaag: 0 } },
  { id: 5, type: 'ontwikkeling', icon: '🌐', typelabel: 'Interessante ontwikkeling', rol: 'Medewerker dienst', naam: 'CTL NHL Stenden', intern: true, spoor: 1, sporeDef: { titel: 'AI & Leren', icon: '🎓' }, laag: 5, titel: 'UvA lanceert eigen AI-chat voor veilig experimenteren', bronLabel: 'CTL NHL Stenden — UvA lanceert eigen AI-chat', tekst: 'De Universiteit van Amsterdam lanceerde een eigen AI-chatomgeving voor veilig experimenteren. Relevant als referentie voor NHL Stenden GPT-NL inzet.', url: 'https://newuniversity.sharepoint.com/sites/center-for-teaching-and-learning/SitePages/UvA-lanceert-eigen-AI-chat--veilig-exp-.aspx', datum: '25 juni 2026', trefwoorden: ['AI-chat', 'Veiligheid', 'Soevereiniteit', 'UvA'], stemmen: { omhoog: 0, omlaag: 0 } },
  { id: 6, type: 'artikel', icon: '📰', typelabel: 'Artikel of publicatie', rol: 'Docent', naam: 'Patrick van Aalst', intern: true, spoor: 1, sporeDef: { titel: 'AI & Leren', icon: '🎓' }, laag: 5, titel: 'AI & the stability of learning tasks', bronLabel: 'CTL NHL Stenden — AI & the stability of learning tasks', tekst: 'CTL-artikel over de impact van AI op de stabiliteit van leeractiviteiten. Vraagt docenten kritisch te kijken welke toetsvormen nog valide zijn in een GenAI-tijdperk.', url: 'https://newuniversity.sharepoint.com/sites/center-for-teaching-and-learning/SitePages/AI-&-the-stability-of-learning-tasks.aspx', datum: '25 juni 2026', trefwoorden: ['Didactiek', 'Toetsing', 'Leeractiviteiten', 'GenAI'], stemmen: { omhoog: 0, omlaag: 0 } },
]

// NHL Stenden organisatiestructuur (uit organogram)
export const NHL_DIENSTEN = [
  'Onderwijs, Onderzoek & Internationalisering (OO&I)',
  'Onderwijslogistiek & Studentondersteuning',
  'Human Resource Management (HRM)',
  'Finance, Control & Procurement (FCP)',
  'Marketing & Communicatie',
  'Digitale Leer- en Werkomgeving (DLWO)',
  'Fysieke Leer- en Werkomgeving (FM)',
]

export const NHL_ACADEMIES = [
  'Academie Educatie',
  'Academie Tech & Design',
  'Academie Gezondheid & Welzijn',
  'Academie Leisure, Tourism & Hospitality',
  'Academie Media, Commercie & Ondernemerschap',
  'Academie Business & Leiderschap',
  'Thorbecke Academie',
]

export const NHL_EXTERN = [
  'SURF',
  'NPULS',
  'AI-Fabriek Groningen',
  'Vereniging Hogescholen',
  'RDI (AI-toezichthouder)',
  'GPT-NL',
  'Anders (vrij invullen)',
]
